name: quran_player_new
description: "A new Flutter project."
publish_to: 'none'

# التحكم في النسخة ورقم البناء
version: 1.1.0+8

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0
  cupertino_icons: ^1.0.8
  flutter_spinbox: ^0.13.1
  google_fonts: ^6.2.1
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/start/
    - assets/hasbuk/
    - assets/ayah_texts.json
    - assets/everyayah_reciters.json
    - assets/logo.png
    - assets/begin/
    - assets/begin/001000.mp3
    - assets/begin/001001.mp3
    # - assets/icon.png
    # - assets/quran_mp3/

  fonts:
    - family: uthmani
      fonts:
        - asset: assets/fonts/KFGQPCAnBold.ttf
